# fly.toml app configuration file generated for leinadest-full-stack-open-pokedex on 2024-06-13T09:22:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leinadest-full-stack-open-pokedex'
primary_region = 'ewr'

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[deploy]
  strategy = "canary"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
